FROM mike0sv/sf_docker_base # создать свой образ на основе образа mike0sv/sf_docker_base
WORKDIR ./Files/
COPY my_files.txt ./ # добавить в него текстовый файл с фразой I know how to use docker ./Files/my_files.txt ./
ENV DATA_PATH ./Files/my_files.txt